### ISSUE TITLE
Current selection shouldn't rely on LayerList.js

### ISSUE THREAD

**Issue by mapsam** [cugos/dropchop#138]
This is mentioned as a `TODO` on [this line](https://github.com/cugos/dropchop/blob/master/src/js/layerlist/LayerList.js#L40). 

We should also start considering creating our own `layers` central hub that other views, such as the mapview and layerlist, can reflect in their own visual manner.

**Comment by alukach** [comment]
Out of curiosity, what would be the win from this refactor? It kind of makes sense to me to have selection be coupled with the layerlist, since it's the layerlist items that are getting selected.  I can also see how this would be limiting though, like if we wanted to allow selecting objects by clicking on map features.  Is that the primary drive?

**Comment by mapsam** [comment]
Mostly the latter - the TODO, which I believe @thebigspoon added reads as follows:

```
**  TODO: selection will not be forever tied to the layerlist (it
**  will be possible to select via click on features or by attributes)
**  meaning that it would be wise to decouple this from layerlist soon
```

**Comment by mapsam** [comment]
Current selection no longer relies on layerlist, and is built into `selection.dropchop.js` section. You can find the current selection in the `dc.selection.list` array.
