### ISSUE TITLE
Need a favicon

### ISSUE THREAD

**Issue by alukach** [cugos/dropchop#155]
Dropchop is definitely needing a cleaver or something as a favicon.

**Comment by mapsam** [comment]
Nice! Could also add an icon from cugos/geoglyphs

**Comment by alukach** [comment]
Cool.  Geoglyphs is looking awesome so far.

**Comment by mapsam** [comment]
Added a geoglyph favicon! 

<img width="221" alt="screen shot 2015-07-12 at 11 53 55 am" src="https://cloud.githubusercontent.com/assets/1943001/8639369/cfbf945e-288c-11e5-83ea-e510c31f94e5.png">

This required adding a new `assets` directory under `src` and creating a new `copy:assets` command to be run with Grunt. Right now these are only copied over when you run the command manually because I wasn't sure where to add this in the build process. Should it be part of the default `grunt` command somewhere?
