### ISSUE TITLE
Getting error with notification.add()

### ISSUE THREAD

**Issue by mapsam** [cugos/dropchop#162]
`Uncaught TypeError: Cannot read property 'add' of undefined`

Coming from this line: https://github.com/cugos/dropchop/blob/geo-menu-updates/src/js/controller/AppController.js#L118 - @alukach does this have to do with the notification changes from #154 ?

**Comment by alukach** [comment]
So based on that link, I'm guessing that this is from the `geo-menu-updates` branch?

Looking at the controller source code, it appears that the [`this.notification = new L.Dropchop.Notifications();`](https://github.com/cugos/dropchop/blob/master/src/js/controller/AppController.js#L24) declaration was removed, likely due to a bad merge.

This appears to have occurred during the [73ecce9](https://github.com/cugos/dropchop/commit/73ecce973bbbb2bc6ec79cfe9a7921a971966805#diff-dd6550659eb3f562e3daf4cb53c84280), although the diff doesn't actually show it being removed (I think I've seen this before, it's a weird thing that can happen with merging where the diffs don't represent changes made in the merge).  Take a look at the the code from commit [73ecce9](https://github.com/cugos/dropchop/blob/73ecce973bbbb2bc6ec79cfe9a7921a971966805/src/js/controller/AppController.js#L21-L32) compared to [the commit before (fd12ff0018)](https://github.com/cugos/dropchop/blob/fd12ff001860abf1703ab70f33359405dc0cb649/src/js/controller/AppController.js#L21-L31).

**Comment by mapsam** [comment]
Should it be added back? Definitely may have scraped it accidentally when merging master into `geo-menu-updates`.

UPDATE: Adding it back fixes, but since it doesn't exist in `master` I feel like something may still be amiss.

**Comment by alukach** [comment]
Yeah, removing it in [this commit](https://github.com/cugos/dropchop/commit/4e2c20cf797598e742a387adb15a5dad1e286ffd#diff-dd6550659eb3f562e3daf4cb53c84280L74) caused the issue.

**Comment by alukach** [comment]
It does exist on `master`: https://github.com/cugos/dropchop/blob/master/src/js/controller/AppController.js#L24

**Comment by mapsam** [comment]
Thanks for finding the commit to blame. Must have been moving through that merge too quickly :stuck_out_tongue_closed_eyes:
