### ISSUE TITLE
Should we start breaking Ops into their own files?

### ISSUE THREAD

**Issue by mapsam** [cugos/dropchop#222]
Seems that https://github.com/cugos/dropchop/blob/master/src/js/ops.file.dropchop.js is getting pretty big, I'm wondering if it would be more welcoming to people to turn these into their own files - would that make more sense? Basically could have an operations folder with small files for each operation.

Would like to hear from @jczaplew, @hamhands, and @npeihl who have recently jumped on the project and needed to touch that file. What would have made sense to you jumping into the project?

**Comment by alukach** [comment]
While I don't want to contaminate the others' thoughts, to me there seemed like some natural groupings that I added in #211: https://github.com/cugos/dropchop/pull/211/files#diff-8db67878f63437c7114acccdf6e81520.

While we're on the topic of files (rather than opening a new Issue), is there a point to ending every file with `dropchop`?  That felt a bit strange to me when they all get concatenated.

**Comment by hamhands** [comment]
+1 ^^^

Seeing a bunch of js files for each operation would be just as intimidating as having them all in one big file IMO. A good middleground is what @alukach suggests.

**Comment by jczaplew** [comment]
`ops.file.dropchop.js` doesn't seem too unwieldy to me.

**Comment by npeihl** [comment]
I'm OK with how it is now. The easiest way for me to start on `load-arcgis` was by seeing how `load-gist` was written in the same file.

**Comment by mapsam** [comment]
Alright, seems best to just keep em all in one file for now.

I think my initial reasoning to name `*.**.dropchop.js` was to mimic the way the actual `dropchop` object worked. Made sense to me at the time, but I have no real legitimate explanation for it now `¯\_(ツ)_/¯`
