### ISSUE TITLE
State of the Chop

### ISSUE THREAD

**Issue by npeihl** [cugos/dropchop#254]
I was reading the CoC for Cugos and ran across this section quoted below.

> Step down considerately.
> Members of every project come and go. When somebody leaves or disengages from the project they should tell people they are leaving and take the proper steps to ensure that others can pick up where they left off. In doing so, they should remain respectful of those who continue to participate in the project and should not misrepresent the project’s goals or achievements. Likewise, community members should respect any individual’s choice to leave the project.

It's been a while since anyone has committed any changes to Dropchop so I just wanted to start a discussion on the project as I see it. This is a volunteer run project and continued development requires a lot of dedicated time from the volunteers. That's time not many of us have. 

I want to say first that I have no intentions of stepping down from this project. In December, I spoke at the Cugos meeting to demo how we could possibly refactor DC to render much larger GeoJSON files using Mapbox-GL. Unfortunately, I am not able to configure the rendering how I want to and decided to wait until Mapbox-GL had data-driven styles. I know the folks at Mapbox are working hard on this and I completely understand how long the process can take. Once data driven styles are available in Mapbox-GL, I will happily take up development again. Until then, I've left my unfinished work in the `mapbox-gl` branch.

**Comment by npeihl** [comment]
Oh holy Hannah! I just now saw that data driven styles dropped today. https://www.mapbox.com/blog/data-driven-styling/

**Comment by wboykinm** [comment]
@npeihl Would this also be the time to broach the turf v3.0 question? I see this is still on v2.0.2

**Comment by mapsam** [comment]
@npeihl I don't know how I missed this initial conversation - apologies for the lack of response!

My reactions:

* awesome CoC reference 😄 
* I've obviously taken a break from committing to the project, mostly because of starting the new job and staying focused there - but also slightly related to a bit of burnout and just wanting to focus on some other things.
* Long term hopes: I'd love to jump back into the project, and am happy to continue merging PRs and thinking through feature requests
* For the sake of maintenance - I think it will be important to completely define the goals of Dropchop, and also define **what Dropchop will never be**. That will get us in a space of making sure this project continues to stay on track of goals, and to allow other ideas that fit outside of the project to become other unique projects instead of being forgetting (i.e. #130 - deserves some honest love)
* re data-driven-styles - they are coming along! Right now they are only working with points, but hopefully things progress into further geometry types

Let me think about this a little more over the next few days. It would be unfair of me/us to stand in the middle, half-committed and delaying 👍 👎 decisions, if there are other folks willing to continue pushing - such as yourself @npeihl!

**Comment by npeihl** [comment]
@wboykinm I'd love to see Turf 3.0 in DropChop! Would love to see a PR if you have time. Or I may take up the project when I have time.

@mapsam Thanks for following up. I like the idea of defining the limits of Dropchop. And revisiting open tickets is important as well. 

I can't see a reason to keep this issue open (Turf 3.0 should be a separate issue), so I'm closing it.

**Comment by mapsam** [comment]
I started cleaning out some open PRs today, getting me excited about dropchop again. Moving slowly, and trying to remember how this all works makes me realize that the gulp/grunt/etc. build ecosystem makes this really hard for beginners (including myself `x` number of months later). I'd propose a mini-sprint trying to harness browserify and `require()` as much as possible whilst reducing dependencies.

cc @nickpeihl

**Comment by nickpeihl** [comment]
@mapsam A mini-sprint sounds like fun. I may have time tomorrow afternoon to hack on it. Getting rid of gulp might be nice. I've long stopped using it.
